# language : 언어(플랫폼) 선택
language: java

# sudo : 관리자 권한 갖기
sudo: required

# sevices : 도커 환경 구성하기
services:
  -docker

# 현재 옵션은 오직 master 브랜치에 push될 때만 수행합니다.
branches:
  only:
    - master

# 메이븐을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정합니다.
# Travis CI 서버의 Home
#cache:
#  directories:
#    - '$HOME/.m2'



# before_install : 스크립트 실행할 수 있는 환경 구성
before_install:
  - chmod +x mvnw
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - echo "before_install■■■■■■■■■■■start creating an image with dockerfile"
# (참고) https://eojin312.github.io/%EA%B0%9C%EC%9D%B8%EA%B3%B5%EB%B6%80/travis/
# (참고) https://brainbackdoor.tistory.com/17



# script : 테스트 실행할 스크립트
script:
  - ./mvnw test -B
  - echo "scrip■■■■■■■■■■■sstart creating an image with dockerfile"
#script: "./mvnw clean package"       <-   여기서는 프로젝트 내부에 둔 mvnw를 통해 clean & package를 수행합니다.


