FROM openjdk:8-jdk-alpine

VOLUME /tmp

EXPOSE 80

# ARG JAR_FILE=restful-web-service-0.0.1-SNAPSHOT.jar  <-- 연습용
ARG JAR_FILE=target/*.jar

ADD ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
